apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: simple-nodejs-app-ozfn
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-eilc-tenant/nodejs-users/simple-nodejs-app-ozfn@sha256:b6306652019b78bbac67bb93997606e051da035d19c77e98cab73dd3ca542bc5
        name: my-nodejs
        resources: {}
status: {}
